version: 2

sources:
  - name: fivetran_linkedin
    database: dbt-bq-training-473915
    schema: linkedin_company_pages

    loader: Fivetran
    loaded_at_field: "_fivetran_synced"
    
    tables:

      # NOUVELLES TABLES AJOUTÉES POUR LE DIMENSION MATCHING:
      - name: geo
      - name: share_statistic
      - name: ugc_post
      - name: organization  
      - name: seniority
      - name: industry        
      - name: function 

      # NOUVELLES TABLES AJOUTÉES POUR LE STAGING Des Stats PAGE
      - name: page_statistic_by_function  # NOUVELLE TABLE DE FAITS
      - name: page_statistic_by_geo  # NOUVELLE TABLE DE FAITS
      - name: page_statistic_by_geo_country  # NOUVELLE TABLE DE FAITS
      - name: page_statistic_by_seniority  # NOUVELLE TABLE DE FAITS
      - name: page_statistic_by_staff_count_range  # NOUVELLE TABLE DE FAITS
    
      # NOUVELLES TABLES AJOUTÉES POUR LE STAGING des FOLLOWERS:
      - name: followers_by_geo_country
      - name: followers_by_industry
      - name: followers_by_function
      - name: followers_by_geo  
      - name: followers_by_seniority
      - name: followers_by_association_type
      - name: followers_by_staff_count_range

      # NOUVELLES TABLES AJOUTÉES POUR LE STAGING des données journalières:
      - name: time_bound_follower_statistic
      - name: time_bound_page_statistic
      - name: time_bound_share_statistic
      - name: total_follower_statistic
      - name: total_page_statistic
      - name: total_share_statistic

      - name: ugc_post_history
      - name: ugc_post_share_statistic